# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!

workspace 'ZWallet'

def common_dependency
  pod 'Kingfisher'
  pod 'OTPFieldView'
end
  
target 'App' do
  pod 'Moya'
  pod 'netfox', :configuration => ['Debug']
  common_dependency
end

target 'Core' do
 project '../Module/Core/Core'
 
 pod 'Moya'
 common_dependency
end

target 'History' do
  project '../Module/History/History'
  
  common_dependency
end

target 'Home' do
  project '../Module/Home/Home'
  
  common_dependency
end

target 'Login' do
  project '../Module/Login/Login'
  
  common_dependency
end

target 'SignUp' do
  project '../Module/SignUp/SignUp'
  
  common_dependency
end

target 'SetupPin' do
  project '../Module/SetupPin/SetupPin'
  
  common_dependency
end

target 'ConfirmOtp' do
  project '../Module/ConfirmOtp/ConfirmOtp'
  
  common_dependency
end

target 'Receiver' do
  project '../Module/Receiver/Receiver'
  
  common_dependency
end

target 'Transfer' do
  project '../Module/Transfer/Transfer'
  
  common_dependency
end

target 'TransferDetail' do
  project '../Module/TransferDetail/TransferDetail'
  
  common_dependency
end

target 'TransferConfirm' do
  project '../Module/TransferConfirm/TransferConfirm'
  
  common_dependency
end

target 'PinConfirm' do
  project '../Module/PinConfirm/PinConfirm'
  
  common_dependency
end

target 'TopUp' do
  project '../Module/TopUp/TopUp'
  
  common_dependency
end
